#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Sempre grava no .env da raiz do projeto, não importa de onde o script é
# chamado — evita criar um .env fantasma em scripts/.
ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env"

GOOGLE_REDIRECT_URI="http://localhost:3000/api/auth/callback/google"
TWITCH_REDIRECT_URI="http://localhost:3000/api/auth/callback/twitch"

TOTAL_STAGES=2

banner "Login com Google e Twitch — VLR Fantasy"

# ── Stage 1: Google ────────────────────────────────────────────────────────
stage "Google: criar credencial OAuth"
say "Para o botão 'Continuar com o Google' aparecer na tela de login, o"
say "Google precisa saber que seu app existe. Isso é feito registrando um"
say "'OAuth client' no Google Cloud Console — leva uns 3 minutos."

if confirm "Quer configurar o login com Google agora?"; then
  say ""
  say "Primeiro, a tela de consentimento (só precisa existir uma vez por projeto):"
  open_url "https://console.cloud.google.com/apis/credentials/consent"
  step "Se pedir para criar um projeto, crie um com qualquer nome (ex: VLR Fantasy)."
  step "Escolha o tipo 'Externo' e clique em Criar."
  step "Preencha nome do app, seu e-mail em 'E-mail de suporte do usuário' e"
  step "  também em 'Informações de contato do desenvolvedor'. Salve e continue"
  step "  até voltar ao painel (não precisa publicar nem adicionar escopos)."
  note "Se você já tinha configurado isso antes neste projeto Google, pode pular direto pra próxima parte."
  pause "Terminou a tela de consentimento (ou já tinha)? Pressione Enter."

  say ""
  say "Agora a credencial em si:"
  open_url "https://console.cloud.google.com/apis/credentials"
  step "Clique em '+ CRIAR CREDENCIAIS' → 'ID do cliente OAuth'."
  step "Tipo de aplicativo: 'Aplicativo da Web'."
  step "Em 'URIs de redirecionamento autorizados', clique '+ ADICIONAR URI' e cole:"
  note "    $GOOGLE_REDIRECT_URI"
  warn "Em produção, troque localhost:3000 pelo seu domínio real (o mesmo de BETTER_AUTH_URL)."
  step "Clique em Criar. Uma janela vai mostrar o Client ID e o Client Secret."

  ask GOOGLE_CLIENT_ID "Cole o Client ID:"
  ask_secret GOOGLE_CLIENT_SECRET "Cole o Client Secret:"
  write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
  write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
else
  note "Pulado. O botão do Google continua oculto até essas duas variáveis existirem."
  SKIPPED+=("Google OAuth — rode este script de novo quando quiser configurar")
fi

# ── Stage 2: Twitch ─────────────────────────────────────────────────────────
stage "Twitch: registrar aplicativo"
say "Mesma ideia, agora com a Twitch, para o botão 'Continuar com a Twitch'."

if confirm "Quer configurar o login com a Twitch agora?"; then
  open_url "https://dev.twitch.tv/console/apps"
  step "Clique em 'Register Your Application'."
  step "Name: qualquer nome (ex: VLR Fantasy)."
  step "Category: 'Website Integration'."
  step "Em 'OAuth Redirect URLs', clique 'Add' e cole:"
  note "    $TWITCH_REDIRECT_URI"
  warn "Em produção, troque localhost:3000 pelo seu domínio real (o mesmo de BETTER_AUTH_URL)."
  step "Clique em 'Create'."
  step "Na lista de apps, clique no app que você acabou de criar."
  step "Copie o 'Client ID' mostrado na página."

  ask TWITCH_CLIENT_ID "Cole o Client ID:"

  step "Clique em 'New Secret' para gerar o Client Secret."
  warn "A Twitch só mostra o secret uma vez — copie antes de sair da página."

  ask_secret TWITCH_CLIENT_SECRET "Cole o Client Secret:"
  write_env TWITCH_CLIENT_ID "$TWITCH_CLIENT_ID"
  write_env TWITCH_CLIENT_SECRET "$TWITCH_CLIENT_SECRET"
else
  note "Pulado. O botão da Twitch continua oculto até essas duas variáveis existirem."
  SKIPPED+=("Twitch OAuth — rode este script de novo quando quiser configurar")
fi

finish

note "Reinicie o servidor de desenvolvimento para o Next.js reler o .env:"
note "  pnpm dev"
note "O login por e-mail e senha continua funcionando normalmente, configurado ou não."
printf '\n'
